/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as IndexImport } from './../routes/index'
import { Route as ErrorsNotFoundImport } from './../routes/errors/not-found'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ErrorsNotFoundRoute = ErrorsNotFoundImport.update({
  id: '/errors/not-found',
  path: '/errors/not-found',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/errors/not-found': {
      id: '/errors/not-found'
      path: '/errors/not-found'
      fullPath: '/errors/not-found'
      preLoaderRoute: typeof ErrorsNotFoundImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/errors/not-found': typeof ErrorsNotFoundRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/errors/not-found'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/errors/not-found'
  id: '__root__' | '/' | '/errors/not-found'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorsNotFoundRoute: typeof ErrorsNotFoundRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorsNotFoundRoute: ErrorsNotFoundRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/errors/not-found"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/errors/not-found": {
      "filePath": "errors/not-found.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
